language: node_js
node_js:
  - 0.10.40
addons:
    code_climate:
        repo_token: 3b02b0fa0647849c47548a030ec9bf35c704feca75b763af3ccdd180ae8afe88
before_script:
  - "mv src/app/config.tpl src/app/config.js"
  - "npm install"
  - "npm install -g bower"
  - "npm install -g gulp@3.9.0"
  - "npm install -g karma@0.13.3"
  - "npm install phantomjs@1.9.17"
  - "bower install"
  - "gulp"
script:
  - "gulp test"

